### ISSUE TITLE
Can use this for Megui??

### ISSUE THREAD

**Issue by kedaitinh12** [AkarinVS/eac3to-wrapper#1]
Sr for noob question. May can fix bug if only copy eac3to-wrapper.exe to same folder with eac3to.exe in Megui?? If not, can you guild me how use this to fix eac3to in Megui??

**Comment by AkarinVS** [comment]
I think it's possible.

Assume you have installed megui to d:\megui.

then you should have eac3to.exe at d:\megui\tools\eac3to\eac3to.exe.

rename d:\megui\tools\eac3to to d:\megui\tools\eac3to.real
mkdir d:\megui\tools\eac3to
and put eac3to-wrapper.exe as d:\megui\tools\eac3to\eac3to.exe

also make sure you have mkvmerge.exe and mkvextract.exe under
d:\megui\tools\mkvtoolnix.

>

**Comment by kedaitinh12** [comment]
To simply just put eac3to-wrapper.exe to same folder with eac3to.exe or deleted eac3to.exe and rename eac3to-wrapper.exe to eac3to.exe??

**Comment by AkarinVS** [comment]
as eac3to-wrapper.exe is only a wrapper around eac3to & mkvextract/mkvmerge
to fix a specific bug of eac3to, unfortunately, using it to replace
eac3to.exe won't work.

Also note that you only need eac3to-wrapper if you use eac3to to extract
PGS subtitles from mkv files.

>

**Comment by kedaitinh12** [comment]
Thanks for your guide

**Comment by kedaitinh12** [comment]
You are developer of eac3to-wrapper so can you answer him
https://forum.doom9.org/showthread.php?p=1959262#post1959262
